# action.yml
name: 'Delete old azure container tags'
description: 'This action will delete all docker images except the latest in the azure container repository'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3 # Checkout the repository content to github runner.

    - uses: actions/setup-python@v3
    - shell:
      run: |
        pip install --pre azure-containerregistry
        pip install --pre azure-identity

    - name: Execute Python script # Run the run.py to get the latest data
      shell:
      run: python del_old_containers.py

