# action.yml
name: 'Delete old azure container tags'
description: 'This action will delete all docker images except the latest in the azure container repository'
inputs:
  creds:
    description: 'Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install Azure cli
      run: |
        sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
        curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
        AZ_REPO=$(lsb_release -cs)
        echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
        sudo apt-get update
        sudo apt-get install azure-cli
    - uses: azure/login@v1
      with:
        creds: ${{ inputs.creds }}

    - uses: actions/checkout@v3 # Checkout the repository content to github runner.

    - uses: actions/setup-python@v3
    - shell:
      run: |
        pip install --pre azure-containerregistry
        pip install --pre azure-identity

    - name: Execute Python script # Run the run.py to get the latest data
      shell:
      run: python del_old_containers.py

