# action.yml
name: 'Delete old azure container tags'
description: 'This action will delete all docker images except the latest in the azure container repository'
inputs:
  acr-name:  # azure container registry
    description: 'Specify the name of the Azure container registry'
    required: true

  repository-name:  # container image name
    description: 'Specify the name of the container image'
    required: true

  latest-tag:  # tag name
    description: 'Specify latest tag. Keep the latest tag and delete all other tags'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3 # Checkout the repository content to github runner.

    - uses: actions/setup-python@v3
    - shell:
      run: |
        pip install --pre azure-containerregistry
        pip install --pre azure-identity

    - name: Execute Python script # Run the run.py to get the latest data
      shell:
      run: python del_old_containers.py --acr-name ${{ inputs.acr-name }} --repository-name ${{ inputs.repository-name }} --latest-tag ${{ inputs.latest-tag }}

