# File: .github/workflows/workflow.yml

on: [push]

name: AzureDeleteOldContainerTags

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: pandareen/delete-old-tags-az@main
        with:
          acr-name: sandeshyapuramcr
          repository-name: hello
          latest-tag:  second