# File: .github/workflows/workflow.yml

on: [push]

name: AzureLoginSample

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: pandareen/delete-old-tags-az@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}